name: Example workflow for CocoaPods using Snyk

on: [push, pull_request]

# jobs:
#   security:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: Run Snyk to check for vulnerabilities
#         uses: snyk/actions/cocoapods@master
#         env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js for installing Snyk 
      uses: actions/setup-node@v2
      with:
        node-version: 18.4

    # Install & prepare Snyk
    - run: npm install --location=global snyk
    
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Open Source Scanning
      run: snyk test --org=6391f850-81f8-48fc-9cd4-aa8c186c6ff0 --all-projects --strict-out-of-sync=true 
# --sarif-file-output=snyk-oss.sarif
#       run: snyk monitor --org=6391f850-81f8-48fc-9cd4-aa8c186c6ff0 --all-projects
      continue-on-error: true

    - name: Snyk-native scanner 
      uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/cocoapods@master
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
          args: --severity-threshold=high
      
#     - name: Upload results to GitHub Open Source Scanning
#       uses: github/codeql-action/upload-sarif@v1
#       with:
#         sarif_file: snyk-oss.sarif
